"""BIST Tahmin Sistemi - Sabitler"""

BIST_HISSELER = {
    "A1CAP — A1 Capital": "A1CAP.IS",
    "ACSEL — Acıselsan": "ACSEL.IS",
    "ADEL  — Adel Kalemcilik": "ADEL.IS",
    "AEFES — Anadolu Efes": "AEFES.IS",
    "AGESA — Agesa Hayat Emeklilik": "AGESA.IS",
    "AGHOL — Anadolu Grubu Holding": "AGHOL.IS",
    "AGYO  — Atakule GYO": "AGYO.IS",
    "AHGAZ — Ahlatcı Gaz": "AHGAZ.IS",
    "AKBNK — Akbank": "AKBNK.IS",
    "AKGRT — Aksigorta": "AKGRT.IS",
    "AKINV — Ak Yatırım": "AKINV.IS",
    "AKSEN — Aksa Enerji": "AKSEN.IS",
    "AKSGY — Akiş GYO": "AKSGY.IS",
    "ALARK — Alarko Holding": "ALARK.IS",
    "ALBRK — Albaraka Türk": "ALBRK.IS",
    "ALKIM — Alkim Kimya": "ALKIM.IS",
    "ALVES — Alves Elektromekanik": "ALVES.IS",
    "ANELE — Anel Elektrik": "ANELE.IS",
    "ANGEN — Agen Kimya": "ANGEN.IS",
    "ANHYT — Anadolu Hayat Emeklilik": "ANHYT.IS",
    "ANSGR — Anadolu Sigorta": "ANSGR.IS",
    "ARCLK — Arçelik": "ARCLK.IS",
    "ARDYZ — Ardıç Yatırım": "ARDYZ.IS",
    "ARENA — Arena Bilgisayar": "ARENA.IS",
    "ARMES — Armes Savunma": "ARMES.IS",
    "ARMGD — Armgold Madencilik": "ARMGD.IS",
    "ARSAN — Arsan Tekstil": "ARSAN.IS",
    "ASELS — Aselsan": "ASELS.IS",
    "ASTOR — Astor Enerji": "ASTOR.IS",
    "ASUZU — Anadolu Isuzu": "ASUZU.IS",
    "ATLAS — Atlas Menkul": "ATLAS.IS",
    "ATSYH — Atlantis Yatırım": "ATSYH.IS",
    "AVGYO — Avrasya GYO": "AVGYO.IS",
    "AVHOL — Avrasya Holding": "AVHOL.IS",
    "AYDEM — Aydem Enerji": "AYDEM.IS",
    "AYEN  — Ayen Enerji": "AYEN.IS",
    "AYGAZ — Aygaz": "AYGAZ.IS",
    "BAGFS — Bagfaş Gübre": "BAGFS.IS",
    "BAYRK — Bayrak Holding": "BAYRK.IS",
    "BERA  — Bera Holding": "BERA.IS",
    "BFREN — Bosch Fren": "BFREN.IS",
    "BIENY — Bien Yapi": "BIENY.IS",
    "BIGCH — Big Chefs": "BIGCH.IS",
    "BIMAS — BİM Mağazalar": "BIMAS.IS",
    "BINHO — Binho Holding": "BINHO.IS",
    "BJKAS — Beşiktaş Futbol": "BJKAS.IS",
    "BNTAS — Bantaş": "BNTAS.IS",
    "BOSSA — Bossa Ticaret": "BOSSA.IS",
    "BRISA — Brisa Bridgestone": "BRISA.IS",
    "BRKO  — Burçelik Kordsa": "BRKO.IS",
    "BRSAN — Borçelik Çelik": "BRSAN.IS",
    "BTCIM — Batıçim": "BTCIM.IS",
    "BUCIM — Bursa Çimento": "BUCIM.IS",
    "BURCE — Burçelik": "BURCE.IS",
    "CANTE — Cantekin Tekstil": "CANTE.IS",
    "CCOLA — Coca-Cola İçecek": "CCOLA.IS",
    "CELHA — Çelik Halat": "CELHA.IS",
    "CEMAS — Çemaş Döküm": "CEMAS.IS",
    "CEOEM — CEO Event": "CEOEM.IS",
    "CGCAM — Çağ Cam": "CGCAM.IS",
    "CIMSA — Çimsa Çimento": "CIMSA.IS",
    "CLEBI — Celebi Hava Servisi": "CLEBI.IS",
    "CMBTN — Çimbeton": "CMBTN.IS",
    "CONSE — Consus Enerji": "CONSE.IS",
    "COSMO — Cosmos Yatırım Holding": "COSMO.IS",
    "CRFSA — Carrefoursa": "CRFSA.IS",
    "CUSAN — Cusan Dış Ticaret": "CUSAN.IS",
    "CVKMD — CVK Madencilik": "CVKMD.IS",
    "DAGI  — Dagi Giyim": "DAGI.IS",
    "DARDL — Dardanel Önentaş": "DARDL.IS",
    "DATA  — Data Bilişim": "DATA.IS",
    "DENGE — Denge Yatırım Holding": "DENGE.IS",
    "DERHL — Der Holding": "DERHL.IS",
    "DERIM — Deri Holding": "DERIM.IS",
    "DESA  — Desa Deri": "DESA.IS",
    "DEVA  — Deva Holding": "DEVA.IS",
    "DGATE — D-Market (Hepsiburada)": "DGATE.IS",
    "DGGYO — Doğu GYO": "DGGYO.IS",
    "DIRIT — Diriteks": "DIRIT.IS",
    "DMSAS — Demisaş Döküm": "DMSAS.IS",
    "DNISI — Deniz Yatırım": "DNISI.IS",
    "DOBUR — Doğuş Otomotiv": "DOBUR.IS",
    "DOCO  — Doğuş Otomotiv": "DOCO.IS",
    "DOHOL — Doğan Holding": "DOHOL.IS",
    "DYOBY — DYO Boya": "DYOBY.IS",
    "DZGYO — Deniz GYO": "DZGYO.IS",
    "EBEBK — Ebebek Mama": "EBEBK.IS",
    "EGGUB — Ege Gübre": "EGGUB.IS",
    "EGPRO — Ege Profil": "EGPRO.IS",
    "EKGYO — Emlak Konut GYO": "EKGYO.IS",
    "EKIZ  — Ekiz Kimya": "EKIZ.IS",
    "EKSUN — Eksun Gıda": "EKSUN.IS",
    "EMKEL — Emkel Elektrik": "EMKEL.IS",
    "ENJSA — Enerjisa Enerji": "ENJSA.IS",
    "ENKAI — Enka İnşaat": "ENKAI.IS",
    "ENTRA — Entra GYO": "ENTRA.IS",
    "EPLAS — Ekoplast": "EPLAS.IS",
    "EREGL — Ereğli Demir Çelik": "EREGL.IS",
    "ERSU  — Ersu Meyve": "ERSU.IS",
    "ESCAR — Escort Teknoloji": "ESCAR.IS",
    "ESCOM — Esco Enerji": "ESCOM.IS",
    "ETILR — Etibank": "ETILR.IS",
    "EUPWR — Europower Enerji": "EUPWR.IS",
    "EUREN — Euro Yatırım": "EUREN.IS",
    "EUYO  — Euro Yatırım Ort.": "EUYO.IS",
    "EYGYO — Egeyapı GYO": "EYGYO.IS",
    "FADE  — Fade Gıda": "FADE.IS",
    "FENER — Fenerbahçe Futbol": "FENER.IS",
    "FLAP  — Flap Kongre": "FLAP.IS",
    "FONET — Fonet Bilgi": "FONET.IS",
    "FORTE — Forte Bilgi": "FORTE.IS",
    "FROTO — Ford Otosan": "FROTO.IS",
    "FZLGY — Fazıl GYO": "FZLGY.IS",
    "GARAN — Garanti Bankası": "GARAN.IS",
    "GARFA — Garanti Faktoring": "GARFA.IS",
    "GEDIK — Gedik Yatırım": "GEDIK.IS",
    "GEDZA — Gediz Ambalaj": "GEDZA.IS",
    "GENIL — Gen İlaç": "GENIL.IS",
    "GENTS — Gentaş": "GENTS.IS",
    "GEREL — Gerele Kablo": "GEREL.IS",
    "GESAN — Gesan Elektrik": "GESAN.IS",
    "GIPTA — Gipta Kimya": "GIPTA.IS",
    "GLCVY — Glc Yapı": "GLCVY.IS",
    "GLYHO — Global Yatırım Holding": "GLYHO.IS",
    "GMTAS — Gimat Gayrimenkul": "GMTAS.IS",
    "GNDUZ — Gündüz Turizm": "GNDUZ.IS",
    "GOKNR — Göknar Holding": "GOKNR.IS",
    "GOLTS — Göltaş Çimento": "GOLTS.IS",
    "GOZDE — Gözde Girişim": "GOZDE.IS",
    "GRSEL — Güriş Holding": "GRSEL.IS",
    "GSDDE — GSD Denizcilik": "GSDDE.IS",
    "GSDHO — GSD Holding": "GSDHO.IS",
    "GSRAY — Galatasaray Sportif": "GSRAY.IS",
    "GUBRE — Gübre Fab. T.A.Ş.": "GUBRE.IS",
    "GUBRF — Gübre Fabrikaları": "GUBRF.IS",
    "HATEK — Hateks Tekstil": "HATEK.IS",
    "HDFGS — Hedef Girişim": "HDFGS.IS",
    "HEKTS — Hektaş": "HEKTS.IS",
    "HTTBT — Hattat Boru": "HTTBT.IS",
    "HUNER — Hünkar Enerji": "HUNER.IS",
    "ICBCT — ICBC Turkey Bank": "ICBCT.IS",
    "IDEAS — İdeas Mühendislik": "IDEAS.IS",
    "IHLAS — İhlas Holding": "IHLAS.IS",
    "IHLGM — İhlas Gazetecilik": "IHLGM.IS",
    "IHYAY — İhlas Yayın Holding": "IHYAY.IS",
    "IMASM — İmaş Motor": "IMASM.IS",
    "INDES — İndeks Bilgisayar": "INDES.IS",
    "INFO  — İnfo Yatırım": "INFO.IS",
    "INTEM — İntema İnşaat": "INTEM.IS",
    "IPEKE — İpek Doğal Enerji": "IPEKE.IS",
    "ISATR — İş Portföy": "ISATR.IS",
    "ISCTR — İş Bankası C": "ISCTR.IS",
    "ISDMR — İsdemir Demir Çelik": "ISDMR.IS",
    "ISGYO — İş GYO": "ISGYO.IS",
    "ISMEN — İş Menkul Değerler": "ISMEN.IS",
    "JANTS — Jantsa Jant": "JANTS.IS",
    "KAPLM — Kaplan Ambalaj": "KAPLM.IS",
    "KAREL — Karel Elektronik": "KAREL.IS",
    "KARSN — Karsan Otomotiv": "KARSN.IS",
    "KCHOL — Koç Holding": "KCHOL.IS",
    "KERVT — Kerevitaş Gıda": "KERVT.IS",
    "KLNMA — Türkiye Kalkınma Bankası": "KLNMA.IS",
    "KLRHO — Kiler Holding": "KLRHO.IS",
    "KONTR — Kontrolmatik Teknoloji": "KONTR.IS",
    "KOPOL — Kordsa Polimer": "KOPOL.IS",
    "KOTON — Koton Mağazacılık": "KOTON.IS",
    "KOZAL — Koza Altın": "KOZAL.IS",
    "KRDMD — Kardemir D": "KRDMD.IS",
    "KRPLAS— Kır Plastik": "KRPLAS.IS",
    "KSTUR — Kuştur Kuşadası": "KSTUR.IS",
    "KTLEV — Katılım Emeklilik": "KTLEV.IS",
    "KUDAS — Kudaş Denizcilik": "KUDAS.IS",
    "KUTPO — Kümaş Manyezit": "KUTPO.IS",
    "LKMNH — Lokman Hekim": "LKMNH.IS",
    "LOGO  — Logo Yazılım": "LOGO.IS",
    "LRSHO — Lares Holding": "LRSHO.IS",
    "LUKSK — Lüks Kadife": "LUKSK.IS",
    "MAALT — Marmara Altın": "MAALT.IS",
    "MACKO — Maçkolik Spor": "MACKO.IS",
    "MAGEN — Medyagen İletişim": "MAGEN.IS",
    "MARTI — Martı Otel": "MARTI.IS",
    "MAVI  — Mavi Giyim": "MAVI.IS",
    "MEDTR — Meditera Tıbbi": "MEDTR.IS",
    "MEGAP — Mega Polietilen": "MEGAP.IS",
    "MEKAG — Meka Mühendislik": "MEKAG.IS",
    "MEPET — Mepet Metro Petrol": "MEPET.IS",
    "MERCN — Mercan Kimya": "MERCN.IS",
    "MERIT — Merit Turizm": "MERIT.IS",
    "MERKO — Merko Gıda": "MERKO.IS",
    "METRO — Metro Ticaret": "METRO.IS",
    "MGROS — Migros": "MGROS.IS",
    "MIATK — Mia Teknoloji": "MIATK.IS",
    "MMCAS — MMC Sanayi": "MMCAS.IS",
    "MNDRS — Menderes Tekstil": "MNDRS.IS",
    "MOBTL — Mobiltek": "MOBTL.IS",
    "MOGAN — Mogaz Petrol": "MOGAN.IS",
    "MPARK — MLP Sağlık": "MPARK.IS",
    "MRGYO — Margü GYO": "MRGYO.IS",
    "NATEN — Naturel Enerji": "NATEN.IS",
    "NETAS — Netaş Telekomünikasyon": "NETAS.IS",
    "NIBAS — Niğbaş Niğde Beton": "NIBAS.IS",
    "NTHOL — Net Holding": "NTHOL.IS",
    "NTTUR — Nettur Turizm": "NTTUR.IS",
    "NUHCM — Nuh Çimento": "NUHCM.IS",
    "OBASE — OBase Bilgi": "OBASE.IS",
    "ODAS  — Odaş Elektrik": "ODAS.IS",
    "ODINE — Odin Tekstil": "ODINE.IS",
    "OFSYM — Ofset Yapımcılık": "OFSYM.IS",
    "ONCSM — Oncem Medya": "ONCSM.IS",
    "ORGE  — Orge Enerji": "ORGE.IS",
    "ORMA  — Orma Orman": "ORMA.IS",
    "OSMEN — Osmanlı Menkul": "OSMEN.IS",
    "OSTIM — Ostim Endüstriyel": "OSTIM.IS",
    "OTKAR — Otokar": "OTKAR.IS",
    "OYAKC — Oyak Çimento": "OYAKC.IS",
    "OZGYO — Özderici GYO": "OZGYO.IS",
    "OZKGY — Özak GYO": "OZKGY.IS",
    "OZRDN — Özradan Yatırım": "OZRDN.IS",
    "OZSUB — Özsu Gıda": "OZSUB.IS",
    "PAGYO — Panora GYO": "PAGYO.IS",
    "PAMEL — Pamel Yenilenebilir": "PAMEL.IS",
    "PAPIL — Papilion Tekstil": "PAPIL.IS",
    "PARSN — Parsan Makine": "PARSN.IS",
    "PASEU — Paşabahçe Cam": "PASEU.IS",
    "PCILT — Pınar Çimento": "PCILT.IS",
    "PEHOL — Pera Holding": "PEHOL.IS",
    "PENGD — Penguen Gıda": "PENGD.IS",
    "PETKM — Petkim": "PETKM.IS",
    "PETUN — Pınar Et": "PETUN.IS",
    "PGSUS — Pegasus Hava Yolları": "PGSUS.IS",
    "PINSU — Pınar Su": "PINSU.IS",
    "PKART — Plastikkart": "PKART.IS",
    "PKENT — Petrokent Turizm": "PKENT.IS",
    "PLTUR — Palmet Turizm": "PLTUR.IS",
    "PNLSN — Panelsan Çelik": "PNLSN.IS",
    "POLHO — Polisan Holding": "POLHO.IS",
    "POLTK — Politeknik Metal": "POLTK.IS",
    "PRKAB — Prysmian Kablo": "PRKAB.IS",
    "PRKME — Park Elektrik": "PRKME.IS",
    "PRZMA — Prizma Pres": "PRZMA.IS",
    "RHEAG — Rhea Girişim": "RHEAG.IS",
    "RODRG — Rodrigo Tekstil": "RODRG.IS",
    "ROYAL — Royal Halı": "ROYAL.IS",
    "RYGYO — Reysaş GYO": "RYGYO.IS",
    "RYSAS — Reysaş Taşımacılık": "RYSAS.IS",
    "SAHOL — Sabancı Holding": "SAHOL.IS",
    "SARKY — Sarkuysan Elektrolitik": "SARKY.IS",
    "SASA  — Sasa Polyester": "SASA.IS",
    "SAYAS — Sayaş Makine": "SAYAS.IS",
    "SDTTR — Sandt Teknoloji": "SDTTR.IS",
    "SEGYO — Servet GYO": "SEGYO.IS",
    "SEKUR — Sekuro Plastik": "SEKUR.IS",
    "SELEC — Selçuk Ecza": "SELEC.IS",
    "SELGD — Selva Gıda": "SELGD.IS",
    "SEYKM — Seydişehir Alüminyum": "SEYKM.IS",
    "SILVR — Silverline Endüstri": "SILVR.IS",
    "SIMAS — Şimşek Ambalaj": "SIMAS.IS",
    "SISE  — Şişe Cam": "SISE.IS",
    "SKBNK — Şekerbank": "SKBNK.IS",
    "SMART — Smart Güneş": "SMART.IS",
    "SNGYO — Sinpaş GYO": "SNGYO.IS",
    "SNKRN — Sanko Enerji": "SNKRN.IS",
    "SNPAM — Sanko Pazarlama": "SNPAM.IS",
    "SODA  — Soda Sanayii": "SODA.IS",
    "SOKM  — Şok Marketler": "SOKM.IS",
    "TABGD — TAB Gıda": "TABGD.IS",
    "TARKM — Tarkim Tarım": "TARKM.IS",
    "TATEN — Tatlıses Enerji": "TATEN.IS",
    "TATGD — Tat Gıda": "TATGD.IS",
    "TAVHL — TAV Havalimanları": "TAVHL.IS",
    "TCELL — Turkcell": "TCELL.IS",
    "TDGYO — Trend GYO": "TDGYO.IS",
    "TEKTU — Tek-Art Turizm": "TEKTU.IS",
    "TEZOL — Tezol Kağıt": "TEZOL.IS",
    "TGSAS — TGS Dış Ticaret": "TGSAS.IS",
    "THYAO — Türk Hava Yolları": "THYAO.IS",
    "TIRE  — Tire Kutsan": "TIRE.IS",
    "TKFEN — Tekfen Holding": "TKFEN.IS",
    "TKURU — Türk Turizm": "TKURU.IS",
    "TLMAN — Telemann Telekom": "TLMAN.IS",
    "TMPOL — Temapol Polimer": "TMPOL.IS",
    "TNZTP — Tınaztepe Hastane": "TNZTP.IS",
    "TOASO — Tofaş Türk Otomobil": "TOASO.IS",
    "TRCAS — Turcas Petrol": "TRCAS.IS",
    "TRGYO — Torunlar GYO": "TRGYO.IS",
    "TRILC — Trilc Yatırım": "TRILC.IS",
    "TSKB  — Türkiye Sınai Kalkınma B.": "TSKB.IS",
    "TSPOR — Trabzonspor": "TSPOR.IS",
    "TTKOM — Türk Telekom": "TTKOM.IS",
    "TTRAK — Türk Traktör": "TTRAK.IS",
    "TUCLK — Tuçluk Tekstil": "TUCLK.IS",
    "TUPRS — Tüpraş": "TUPRS.IS",
    "TUREX — Tureks Turizm": "TUREX.IS",
    "TURGG — Türkerler Holding": "TURGG.IS",
    "ULKER — Ülker Bisküvi": "ULKER.IS",
    "ULUUN — Ulusoy Un": "ULUUN.IS",
    "UMPAS — Umpaş Holding": "UMPAS.IS",
    "UNLU  — Ünlü Tekstil": "UNLU.IS",
    "USAK  — Uşak Seramik": "USAK.IS",
    "USDMR — Uzmar Gemi": "USDMR.IS",
    "UTPYA — Utopya Turizm": "UTPYA.IS",
    "UVITE — Uvite Teknoloji": "UVITE.IS",
    "VAKBN — Vakıfbank": "VAKBN.IS",
    "VANGD — Van Gölü Enerji": "VANGD.IS",
    "VBTYZ — VBT Yazılım": "VBTYZ.IS",
    "VERTU — Vertu Yatırım": "VERTU.IS",
    "VERUS — Verus Yatırım": "VERUS.IS",
    "VESBE — Vestel Beyaz Eşya": "VESBE.IS",
    "VESTL — Vestel Elektronik": "VESTL.IS",
    "VKFYO — Vakıf Finansal Kiralama": "VKFYO.IS",
    "VKGYO — Vakıf GYO": "VKGYO.IS",
    "YAPRK — Yaprak Süt": "YAPRK.IS",
    "YATAS — Yataş Yatak": "YATAS.IS",
    "YBTAS — Yıldız Boru": "YBTAS.IS",
    "YEOTK — Yeo Teknoloji": "YEOTK.IS",
    "YESIL — Yeşil Girişim": "YESIL.IS",
    "YGGYO — Yeni Gimat GYO": "YGGYO.IS",
    "YGYO  — Yeni Mağazacılık GYO": "YGYO.IS",
    "YKBNK — Yapı Kredi Bankası": "YKBNK.IS",
    "YKSLN — Yükseliş GYO": "YKSLN.IS",
    "YUNSA — Yünsa Yünlü": "YUNSA.IS",
    "YYAPI — Yesil Yapi": "YYAPI.IS",
    "ZEDUR — Zedur Enerji": "ZEDUR.IS",
    "ZOREN — Zorlu Enerji": "ZOREN.IS",
    "ZTPFK — Ziraat Katılım": "ZTPFK.IS",
}




# ─────────────────────────────────────────────────────────────────────────────
# SEKTÖR MOMENTUMu için hisse gruplaması
# ─────────────────────────────────────────────────────────────────────────────
SEKTOR_GRUPLAR = {
    "AKBNK": ["GARAN","ISCTR","YKBNK","VAKBN"],
    "GARAN": ["AKBNK","ISCTR","YKBNK","VAKBN"],
    "ISCTR": ["AKBNK","GARAN","YKBNK","VAKBN"],
    "YKBNK": ["AKBNK","GARAN","ISCTR","VAKBN"],
    "VAKBN": ["AKBNK","GARAN","ISCTR","YKBNK"],
    "THYAO": ["PGSUS","TAVHL"],
    "PGSUS": ["THYAO","TAVHL"],
    "EREGL": ["KRDMD","ISDMR"],
    "KRDMD": ["EREGL","ISDMR"],
    "TOASO": ["FROTO","ASUZU"],
    "FROTO": ["TOASO","ASUZU"],
    "BIMAS": ["MGROS","SOKM"],
    "MGROS": ["BIMAS","SOKM"],
    "KCHOL": ["SAHOL","AGHOL"],
    "SAHOL": ["KCHOL","AGHOL"],
    "ASELS": ["ASELSAN","FNSS"],
    "TCELL": ["TTKOM"],
    "TUPRS": ["PETKM"],
    "PETKM": ["TUPRS"],
}

MAKRO_TICKERLAR = {
    "USDTRY":  "USDTRY=X",   "EURTRY":  "EURTRY=X",
    "ALTIN":   "GC=F",        "PETROL":  "CL=F",
    "BIST100": "XU100.IS",    "BIST30":  "XU030.IS",
    "SP500":   "^GSPC",       "VIX":     "^VIX",
    "DXY":     "DX-Y.NYB",
    # Sektör endeksleri kaldırıldı — rate limit azaltmak için
}

# ─────────────────────────────────────────────────────────────────────────────
# MODEL PARAMETRELERİ — Optimize edilmiş
# ─────────────────────────────────────────────────────────────────────────────
PENCERE        = 40
EPOCH          = 100
BATCH          = 32
TEST_ORANI     = 0.15
HEDEF_GUN      = 10   # 5 → 10 gün (orta vadeli)
HEDEF_ESIK     = 0.025
MIN_HACIM_TL   = 1_000_000
VARSAYILAN_YIL = 15  # maksimum veri: 15 yıl

# Hisseleri alfabetik sırala
BIST_HISSELER = dict(sorted(BIST_HISSELER.items(), key=lambda x: x[0]))

# ─────────────────────────────────────────────────────────────────────────────
# YFINANCE OTURUM YARDIMCISI — Rate limit & cookie sorununu çözer
# ─────────────────────────────────────────────────────────────────────────────
def _yf_session():
    """Tarayıcı gibi davranan özel requests session döndürür."""
    s = requests.Session()
    s.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "tr-TR,tr;q=0.9,en;q=0.8",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
    })
    # Önce ana sayfaya git — cookie al
    try:
        s.get("https://finance.yahoo.com", timeout=5)
    except Exception:
        pass
    return s




# ─────────────────────────────────────────────────────────────────────────────
# TÜRKÇE DUYGU ANALİZİ — Genişletilmiş kelime hazinesi
# ─────────────────────────────────────────────────────────────────────────────
POZITIF = {
    # Güçlü pozitif (ağırlık 2)
    "rekor":2,"zirve":2,"fırladı":2,"coştu":2,"beklentileri aştı":2,
    "tarihi yüksek":2,"güçlü büyüme":2,"kâr açıkladı":2,"temettü artışı":2,
    "anlaşma imzaladı":2,"ihale kazandı":2,"kapasite artırıyor":2,
    "yüksek kâr":2,"borsada lider":2,"yatırımcı ilgisi":2,
    # Orta pozitif (ağırlık 1)
    "yükseliş":1,"artış":1,"büyüme":1,"kâr":1,"kazanç":1,"güçlü":1,
    "başarı":1,"olumlu":1,"yatırım":1,"ihracat":1,"talep":1,
    "toparlanma":1,"iyileşme":1,"temettü":1,"anlaşma":1,"sözleşme":1,
    "sipariş":1,"kapasite":1,"ihracat artışı":1,"pazar payı":1,
    "alım":1,"destek":1,"pozitif":1,"rally":1,"momentum":1,
    "ralli":1,"yeni müşteri":1,"büyük proje":1,"güvenli liman":1,
}
NEGATIF = {
    # Güçlü negatif (ağırlık 2)
    "çöktü":2,"iflas":2,"kriz":2,"soruşturma":2,"dava":2,
    "manipülasyon":2,"haciz":2,"büyük zarar":2,"sermaye kaybı":2,
    "ihracat yasağı":2,"yaptırım":2,"olağanüstü hal":2,
    "devalüasyon":2,"yüksek enflasyon":2,"faiz artışı şoku":2,
    # Orta negatif (ağırlık 1)
    "düşüş":1,"kayıp":1,"zarar":1,"risk":1,"enflasyon":1,
    "gerileme":1,"olumsuz":1,"endişe":1,"panik":1,"baskı":1,
    "zayıf":1,"daralma":1,"küçülme":1,"uyarı":1,"volatilite":1,
    "satış baskısı":1,"zayıf talep":1,"gelir düşüşü":1,"maliyet artışı":1,
    "borç":1,"yükümlülük":1,"temerrüt":1,"erteleme":1,"iptal":1,
}


